### ISSUE TITLE
null dereference when landing at first base

### ISSUE THREAD

**Issue by tantalor** [EngineersNeedArt/Mooncraft2000#1]
I carried landed at a base (green) and the game froze with this this error,
```
Uncaught TypeError: Cannot read properties of null (reading '0')
    at Object.handleGameState (MoonDebriefState.js:170:36)
    at _gameLoop (Mooncraft.js:287:35)
```

Looks like `departedLocation[0]` fails because `departedLocation` is null.

**Comment by tantalor** [comment]
It happens when `locationForBase` returns null, because `baseDeparted` is null, because there is no value for `MOONCRAFT0_BASEDEPARTED` in local storage.

**Comment by tantalor** [comment]
My local storage has these keys:

```
[
    "MOONCRAFT0_LASTYAW",
    "MOONCRAFT0_LASTXPOS",
    "MOONCRAFT0_LASTZPOS",
    "MOONCRAFT0_DISPLAYFPS",
    "MOONCRAFT0_CARGOMOVED",
    "MOONCRAFT0_BASEVISITS",
    "MOONCRAFT0_LASTYPOS"
]
```

**Comment by edward-bailey** [comment]
I've also gotten stuck with this same error, 

It occurs if you 

- Take off and land at the same starting base
- Land at a base not expecting you

The user is not able to progress pass the debrief screen

**Comment by EngineersNeedArt** [comment]
I made a tweak to try to (hopefully) address this. I put up on my server as well. See if it works for you.

The "fix" I made was to provide a default if `NULL` is returned for `MOONCRAFT0_BASEDEPARTED`. Since I assume you just started the game, 'PRB' makes a reasonable default value.

**Comment by edward-bailey** [comment]
Fastest way to reproduce, simply press the space bar once at the start and the game loops around to a debrief before getting stuck.

![image](https://user-images.githubusercontent.com/68242119/165116537-f9f9aa61-3f2f-4007-8b0d-d6feaabe513c.png)

**Comment by edward-bailey** [comment]
> I made a tweak to try to (hopefully) address this. I put up on my server as well. See if it works for you.
> 
> The "fix" I made was to provide a default if `NULL` is returned for `MOONCRAFT0_BASEDEPARTED`. Since I assume you just started the game, 'PRB' makes a reasonable default value.

This seems to have solved it for me
